/**
 * @behaviour
 * @r-id R-001-2
 * @r-ids R-001-2,R-001-6
 */
// Generated by .binaryos/scripts/asset-test-gen.sh — do not hand-edit.
// @asset tier (file-system parity assertions). Regenerated when scope.md changes.
// Pitch: 028-fw-cli-rollout-server-typecheck-cleanup, Scope: 001
import { describe, it, expect } from 'bun:test';
import { readFileSync, existsSync, statSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execSync } from 'node:child_process';

const REPO_ROOT = execSync('git rev-parse --show-toplevel').toString().trim();

function collectTsFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectTsFiles(full));
    else if (entry.isFile() && /\.ts$/.test(entry.name)) out.push(full);
  }
  return out;
}

describe('@asset scope-001 must-not-contain guards', () => {
  const cases = [
    {
      rid: 'R-001-2',
      kind: 'must-not-contain',
      path: 'packages/fw-plugins/src/plugins/fireweave/mcp/rollout-server/dist/types.d.ts',
      pattern:
        'from [\'"](zod|simple-git|@modelcontextprotocol|@fireweaveai\\/fw-rollout-types)[\'"]',
      flags: '',
    },
    {
      rid: 'R-001-6',
      kind: 'must-not-contain',
      path: 'packages/fw-cli/tsconfig.json',
      pattern: '@fireweaveai\\/rollout-server',
      flags: '',
    },
  ];

  it.each(cases)(
    '$rid $kind: $path',
    ({ kind, path, pattern, patterns, flags }: any) => {
      const abs = resolve(REPO_ROOT, path);

      // must-not-contain: tolerant of deleted target (D1) and directory target (D2)
      if (kind === 'must-not-contain') {
        if (!existsSync(abs)) return;
        if (statSync(abs).isDirectory()) {
          for (const file of collectTsFiles(abs)) {
            const body = readFileSync(file, 'utf8');
            expect(body).not.toMatch(new RegExp(pattern, flags));
          }
          return;
        }
        const body = readFileSync(abs, 'utf8');
        expect(body).not.toMatch(new RegExp(pattern, flags));
        return;
      }

      // All other kinds require the file to exist.
      expect(existsSync(abs)).toBe(true);
      if (kind === 'file-exists') return;

      const body = readFileSync(abs, 'utf8');

      // file-content-multi: assert each pattern independently (D4)
      if (kind === 'file-content-multi') {
        for (const p of patterns as string[]) {
          expect(body).toMatch(new RegExp(p, flags));
        }
        return;
      }

      if (
        kind === 'file-content' ||
        kind === 'ddl-parity' ||
        kind === 'generated-spec'
      ) {
        expect(body).toMatch(new RegExp(pattern, flags));
        return;
      }

      throw new Error(`unknown @asset kind: ${kind}`);
    }
  );
});
