// GENERATED by packages/fw-plugins/scripts/codegen-bridge-manifest.ts.
// DO NOT EDIT BY HAND. Regenerate via `bun run codegen:bridge-manifest`.
// Source: apps/fw-server/openapi.json
import { z } from 'zod';

export interface BridgeManifestEntry {
  verb: string;
  path: string;
  inputSchema: z.ZodType;
  responseShape: z.ZodType;
}

export const bridgeManifest: Record<string, BridgeManifestEntry> = {
  add_rollout_participant: {
    verb: 'POST',
    path: '/v1/rollouts/{id}/participants',
    inputSchema: z.object({ id: z.string() }),
    responseShape: z.unknown(),
  },
  cancel_rollout: {
    verb: 'POST',
    path: '/v1/rollouts/{id}/cancel',
    inputSchema: z.object({ id: z.string() }),
    responseShape: z.unknown(),
  },
  get_project_capabilities: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/capabilities',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  get_project_integrations: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/integrations',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  get_recommendation_data: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/rollouts/recommendation-data',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  get_rollout_status: {
    verb: 'GET',
    path: '/v1/rollouts/{id}',
    inputSchema: z.object({ id: z.string() }),
    responseShape: z.unknown(),
  },
  list_open_rollouts: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/rollouts',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  list_project_environments: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/environments',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  list_project_repos: {
    verb: 'GET',
    path: '/v1/projects/{projectId}/repos',
    inputSchema: z.object({ projectId: z.string() }),
    responseShape: z.unknown(),
  },
  list_projects: {
    verb: 'GET',
    path: '/v1/projects',
    inputSchema: z.object({}).passthrough(),
    responseShape: z.unknown(),
  },
  provision_managed_posthog: {
    verb: 'POST',
    path: '/v1/managed-posthog/provision',
    inputSchema: z.object({}).passthrough(),
    responseShape: z.unknown(),
  },
  record_recommendation_outcome: {
    verb: 'POST',
    path: '/v1/rollouts/{id}/recommendation-outcomes',
    inputSchema: z.object({ id: z.string() }),
    responseShape: z.unknown(),
  },
  register_rollout: {
    verb: 'POST',
    path: '/v1/rollouts',
    inputSchema: z.object({}).passthrough(),
    responseShape: z.unknown(),
  },
  seal_rollout: {
    verb: 'POST',
    path: '/v1/rollouts/{id}/seal',
    inputSchema: z.object({ id: z.string() }),
    responseShape: z.unknown(),
  },
  update_participant_sha: {
    verb: 'PATCH',
    path: '/v1/rollouts/{id}/participants/{participantId}',
    inputSchema: z.object({ id: z.string(), participantId: z.string() }),
    responseShape: z.unknown(),
  },
};